### ISSUE TITLE
[4pt]  - Create feature: add new reservation - Student C

### ISSUE THREAD

**Issue by redmarverick** [redmarverick/MMDB#7]
Implement the "add new reservation" form on the Reservations pop up according to the wireframe:

<img width="364" alt="Screenshot 2021-06-27 at 22 35 30" src="https://user-images.githubusercontent.com/7466903/123558708-00010600-d798-11eb-9dda-8d116f0e6a5c.png">

When the user clicks on the "Reserve" button, the data is recorded in the Involvement API and the screen is updated

**Comment by mpa-mxiang** [comment]
Since we are working as a group of two people, this task would not be required as necessary.
